name: 'Moimai-sso'
services:
  postgres-sso-service:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    command: ["postgres", "-p", "5433"]

  sso:
    build: .
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      - postgres-sso-service
    environment:
      - DB_URL=postgresql+asyncpg://postgres:root@postgres-sso-service:5433/postgres
      - SECRET_KEY=M&6u_hdJ-)Qvx:yGkN+2|1a917e3c181d9399a72327e00f78ff8a9992aeea|3ae318fbdc247ce171ea90c244cc46e4